### ISSUE TITLE
GlyphsInfo badly migrated

### ISSUE THREAD

**Issue by thlinard** [googlefonts/tools#1]
https://github.com/googlefonts/tools/tree/master/util/GlyphsInfo returns a 404 error.

**Comment by davelab6** [comment]
@graphicore please could you fix this? :)

**Comment by graphicore** [comment]
related graphicore/googleFontsTools#1

**Comment by rsheeter** [comment]
Fixed by #2. Thanks for the report.

**Comment by davelab6** [comment]
Despite merging #2, https://github.com/googlefonts/tools/tree/master/util/GlyphsInfo still 404s for me :)

**Comment by graphicore** [comment]
Yeah, if navigate to it via the [github interface](https://github.com/googlefonts/tools/tree/master/util) you'll end up here: https://github.com/schriftgestalt/GlyphsInfo/tree/e33ccf3515cc5b8005a3a50b4163663623649d20 I think that redirection was broken before.

**Comment by davelab6** [comment]
Hah ok, thanks for confirming
