### ISSUE TITLE
Runtime error "ImportError: No module named util"

### ISSUE THREAD

**Issue by mathieuruellan** [googlefonts/tools#27]
Hello,

I installed gftools on a debian strech with python/pip.

The execution fails:

```
$ gftools compare-font DroidSansJapanese.ttf DroidSansJapanese.ttf
Traceback (most recent call last):
  File "/usr/local/bin/gftools-compare-font.py", line 69, in <module>
    from util import google_fonts as fonts
ImportError: No module named util
```

Same error in a fresh install in a docker.
Have i missed something?

kind regards

**Comment by felipesanches** [comment]
Thanks for reporting this. I'm aware of the issue and will be providing a fix soon.

**Comment by felipesanches** [comment]
For the record, this is a packaging issue. We need to add the code from the util subdirectory to the python package as well. I failed to notice that on the initial migration of code from Fontbakery into gftools and the resulting migration of scripts from the rootdir into the bin subdirectory in this repo.

**Comment by felipesanches** [comment]
If you really-really need the scripts right now, then you may be able to use the code as it was a few commits in the past, prior to the migration to the bin subdir. But you probably won't have to resort to that since I'll soon provide a fix to this issue.

Sorry for the trouble I may have momentarily caused here.

**Comment by mathieuruellan** [comment]
Fine! Thank you!

2017-11-09 18:34 GMT+01:00 Felipe Corrêa da Silva Sanches <
notifications@github.com>:

**Comment by felipesanches** [comment]
I've just merged the packaging code. Can you try this?

* clone this repo
* create a virtual env
* pip install -e .
* then try to run the scripts

Let me know if that's good enough or if you think something's still missing.

**Comment by mathieuruellan** [comment]
It works like a charm.


2017-11-09 19:31 GMT+01:00 Felipe Corrêa da Silva Sanches <
notifications@github.com>:

**Comment by felipesanches** [comment]
awesome!
