### ISSUE TITLE
Note on unit tests

### ISSUE THREAD

**Issue by davelab6** [googlefonts/tools#32]
The stuff from the GF eng team is actually maintained by them on a company internal vcs, so they expect to be able to push out updating changes; if you patch their stuff, they need to patch their upstream too to keep them in sync.... Therefore I removed direct write access so that changes need to be via PR and they will approve them. 

There was some unit tests they wrote and kept on the internal vcs and they left them out of the external export for reasons unknown, so that means they can't take upstream the tests here, and this means the current tests will get overwritten when they next push.

**Comment by felipesanches** [comment]
yeah, requiring PRs for all changes sounds great!

Do you have any feedback from the internal GF eng team whether the recent changes commited in this repo are good?

**Comment by davelab6** [comment]
No feedback right now :)

**Comment by felipesanches** [comment]
no problem. Let me know when you hear from them.

I noticed that I can't merge PRs anymore. But I think that's your intention indeed, right? Is it @rsheeter who'll be reviewing and merging PRs from now one in this repo?

I have a pending PR right now. After that I was planning to push a new release to pypi because #33 fixes an important packaging bug. When preparing a new release I'll probably also not be able to push a git tag as usual to this repo, right?

**Comment by davelab6** [comment]
Yes, that's the intention :) I guess you'll need to file issues when you
want tags

On Nov 18, 2017 4:25 PM, "Felipe Corrêa da Silva Sanches" <
notifications@github.com> wrote:

no problem. Let me know when you hear from them.

I noticed that I can't merge PRs anymore. But I think that's your intention
indeed, right? Is it @rsheeter <https://github.com/rsheeter> who'll be
reviewing and merging PRs from now one in this repo?

I have a pending PR right now. After that I was planning to push a new
release to pypi because #33 <https://github.com/googlefonts/tools/pull/33>
fixes an important packaging bug. When preparing a new release I'll
probably also not be able to push a git tag as usual to this repo, right?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/googlefonts/tools/issues/32#issuecomment-345472417>,
or mute
the thread

**Comment by felipesanches** [comment]
ok, cool. I'll keep that in mind.
