### ISSUE TITLE
Duplicate dagger and daggerdbl

### ISSUE THREAD

**Issue by asaumierdemers** [googlefonts/tools#43]
Duplicate entry for dagger and daggerdbl in 3 files:

`GF-latin-plus_unique-glyphs.nam`
`filter lists/nice names/plus_unique-glyphs.txt`
`filter lists/uni names/plus_unique-glyphs.txt`

**Comment by alexeiva** [comment]
GF Latin Plus glyphs sets are available in three different formats: `.nam`, `nice-names-`, and `uni-names-` filter lists for Glyphs App.

**Comment by asaumierdemers** [comment]
@alexeiva I know that. 

Check these 4 lines:

https://github.com/googlefonts/tools/blob/master/encodings/GF%20Glyph%20Sets/GF-latin-plus_unique-glyphs.nam#L316

```
0x2020 † DAGGER
0x2020 † DAGGER
0x2021 ‡ DOUBLE DAGGER
0x2021 ‡ DOUBLE DAGGER
```
Same issue for the other files I mentioned earlier.
